//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fbla_app_ui.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizAnswer
    {
        public int ID { get; set; }
        public int QuestionID { get; set; }
        public string Answer { get; set; }
        public string AnswerType { get; set; }
        public bool CorrectAnswer { get; set; }
        public string WhyCorrectAnswer { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
